// Code generated by MockGen. DO NOT EDIT.
// Source: ./manager.go

// Package mock_session is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionManagerInterface is a mock of SessionManagerInterface interface.
type MockSessionManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerInterfaceMockRecorder
}

// MockSessionManagerInterfaceMockRecorder is the mock recorder for MockSessionManagerInterface.
type MockSessionManagerInterfaceMockRecorder struct {
	mock *MockSessionManagerInterface
}

// NewMockSessionManagerInterface creates a new mock instance.
func NewMockSessionManagerInterface(ctrl *gomock.Controller) *MockSessionManagerInterface {
	mock := &MockSessionManagerInterface{ctrl: ctrl}
	mock.recorder = &MockSessionManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManagerInterface) EXPECT() *MockSessionManagerInterfaceMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockSessionManagerInterface) DeleteSession(cookie *http.Cookie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", cookie)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionManagerInterfaceMockRecorder) DeleteSession(cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionManagerInterface)(nil).DeleteSession), cookie)
}

// GetIdFromContext mocks base method.
func (m *MockSessionManagerInterface) GetIdFromContext(ctx context.Context) (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdFromContext", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetIdFromContext indicates an expected call of GetIdFromContext.
func (mr *MockSessionManagerInterfaceMockRecorder) GetIdFromContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdFromContext", reflect.TypeOf((*MockSessionManagerInterface)(nil).GetIdFromContext), ctx)
}

// SetSession mocks base method.
func (m *MockSessionManagerInterface) SetSession(w http.ResponseWriter, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSession", w, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSession indicates an expected call of SetSession.
func (mr *MockSessionManagerInterfaceMockRecorder) SetSession(w, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockSessionManagerInterface)(nil).SetSession), w, id)
}
