
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test ./... -v -coverpkg=./... -coverprofile=cover.out.tmp 

    -name: Delete mock and proto files from coverprofile
      run: cat cover.out.tmp | grep -v "mock.go" | grep -v "pb.go" > cover.out

    -name: Calculate coverage
      run: go tool cover -func=cover.out
