name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: [ '*' ]
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: |
          go get -u -d gocv.io/x/gocv
          golangci/golangci-lint-action@v2
        